Implementing new FLEdge CRD to manage and authenticate the spire-agent
katulu-io/fl-suite pull request #26
Opened 2022-07-21 14:37 UTC by GerardoGR

2022-08-09 09:53 UTC, nfnt requested changes
This is looking good already, though we have to have some more discussions on the controller: The current flow of mutating a spec as part of its `Reconcile` function would mean that the spec of the resources no longer describes what state is being expected, but rather make the declarative spec an imperative one. Let's find a solution for this, that would still conform to the declarative idea of CRDs.

2022-08-09 09:53 UTC, nfnt commented on components/fl-operator/controllers/fledge_controller.go
> +		RequeueAfter: time.Second * 5,
Is there a need to re-run the reconcile loop every 5 seconds? If not, let's keep the default behaviour (by returning `ctrl.Result{}, nil`, which will run the loop every time a dependent resource has been changed.

2022-08-09 09:53 UTC, nfnt commented on components/fl-operator/controllers/fledge_controller.go
> +	if err != nil {
Nit: This can be done in a single line with:
```go
if err := r.Get(ctx, req.NamespacedName, flEdge); err != nil {
```

Here and below for all functions that return `error`.

2022-08-09 09:53 UTC, nfnt commented on components/fl-operator/controllers/fledge_controller.go
> +		Owns(&appsv1.Deployment{}).
This means that `Reconcile` will be called for the respective `FlEdge` if any of these dependent resources changes status. Currently, in `Reconcile` we only check if `flEdge.Spec.Auth.Spire` isn't set yet and create a spire agent in that case. With watching these resources for changes we have to rather: a) Check if changes made to these dependent resources still match whats configured in the `FlEdge` resource, b) recreate or restart "non-conformant" dependent resources.
This currently isn't done in `Reconcile`. Let's either implement this behaviour or add some comments that this is currently not done and implement it in a later commit to keep this PR small.

2022-08-09 09:53 UTC, nfnt commented on components/fl-operator/controllers/fledge_controller.go
> +	if flEdge.Spec.Auth.Spire != nil {
A controller mutating its own spec as part of `Reconcile` is contrary to the purpose of a controller, which is ensuring that the state described in the spec matches the one of its managed resources.
This state could be handles as part of `FlEdge.Status` but I'm not sure if the spec would then have enough information to have a 1-to-1 mapping from spec to the manages resources.

2022-08-09 11:30 UTC, GerardoGR commented on components/fl-operator/controllers/fledge_controller.go
> +	if err != nil {
I think this is more a matter of taste. I can change it, but I think we need to make this a part of the code-style to avoid the back-and-forth.

2022-08-09 11:42 UTC, nfnt commented on components/fl-operator/controllers/fledge_controller.go
> +		Owns(&appsv1.Deployment{}).
This is actually done by using `Patch` to create or update the resources. I'm resolving this.

2022-08-09 11:42 UTC, nfnt commented on components/fl-operator/controllers/fledge_controller.go
> +	if err != nil {
Good point. If this isn't enforced by our linters, it's just taste.

2022-08-09 13:00 UTC, GerardoGR commented on components/fl-operator/controllers/fledge_controller.go
> +		RequeueAfter: time.Second * 5,
Good point!. I based some of the work from the [floperator_controller](https://github.com/katulu-io/fl-suite/blob/beta/components/fl-operator/controllers/floperator_controller.go#L205) and I forgot to amend this return. I'll change it to the default.

2022-08-10 06:45 UTC, nfnt approved these changes
LGTM!

2022-08-10 07:40 UTC, merged